version: '3.7'

services:
    # MySQL
    db:
        container_name: ${APP_NAME}-mysql8
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        image: mysql:8.0.25
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_TCP_PORT: ${DB_PORT}
        ports:
            - '${DB_PORT}:${DB_PORT}'
        security_opt:
            - seccomp:unconfined
        volumes:
            - './virtuagym-docker/db/data:/var/lib/mysql'
            - './virtuagym-docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
            - './virtuagym-docker/db/sql:/docker-entrypoint-initdb.d'
    web:
        container_name: ${APP_NAME}-webserver
        image: nginx:latest
        restart: always
        #environment:
        #  - PANEL_PORT=8082
        ports:
            - '8086:8086'
        volumes:
            - ./:/var/www/html/
            - ./virtuagym-docker/panel.conf:/etc/nginx/conf.d/panel.conf
        extra_hosts:
            - "host.docker.internal:host-gateway"
    php:
        container_name: ${APP_NAME}-php
        build:
            context: virtuagym-docker/
        restart: always
        user: "1000:1000"
        volumes:
            - ./:/var/www/html/
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - db
