version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: virtuagym
        container_name: travellist-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - virtuagym

    db:
        image: mysql:8.0
        container_name: virtuagym-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "${DB_LOCAL_PORT}:${DB_PORT-3306}"
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - virtuagym

    nginx:
        image: nginx:alpine
        container_name: virtuagym-nginx
        restart: unless-stopped
        ports:
            - "8086:8086"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - virtuagym

networks:
    virtuagym:
        driver: bridge
